// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQCT6ROO6csao35wtB70k-ow0-c7Mzd4',
    appId: '1:359947632947:web:4dc78637cedac4081ebe46',
    messagingSenderId: '359947632947',
    projectId: 'yapiventa',
    authDomain: 'yapiventa.firebaseapp.com',
    storageBucket: 'yapiventa.firebasestorage.app',
    measurementId: 'G-PM8T6SR4CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9c0O0lEtVsKl-_pWoUknWsWqtdrLGaI',
    appId: '1:359947632947:android:67993841ad6953dd1ebe46',
    messagingSenderId: '359947632947',
    projectId: 'yapiventa',
    storageBucket: 'yapiventa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbXq0H-WafCiy8NNkC0aIOAX3OK6iOJs',
    appId: '1:359947632947:ios:9da06812f7d4778e1ebe46',
    messagingSenderId: '359947632947',
    projectId: 'yapiventa',
    storageBucket: 'yapiventa.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvbXq0H-WafCiy8NNkC0aIOAX3OK6iOJs',
    appId: '1:359947632947:ios:9da06812f7d4778e1ebe46',
    messagingSenderId: '359947632947',
    projectId: 'yapiventa',
    storageBucket: 'yapiventa.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzQCT6ROO6csao35wtB70k-ow0-c7Mzd4',
    appId: '1:359947632947:web:0672dad2a4c431e41ebe46',
    messagingSenderId: '359947632947',
    projectId: 'yapiventa',
    authDomain: 'yapiventa.firebaseapp.com',
    storageBucket: 'yapiventa.firebasestorage.app',
    measurementId: 'G-1VZ13NZMBC',
  );
}
